# @package _global_
benchmark_id: nasengb
task_id: ${task.name}
task:
  _target_: carps.utils.task.Task
  name: nasengb/PDEVar
  seed: ${seed}
  objective_function:
    _target_: carps.objective_functions.botorch.BOTorchObjectiveFunction
    botorch_problem:
      _target_: naseng_benchmark.pdes.PDEVar
    seed: ${seed}
  input_space:
    _target_: carps.utils.task.InputSpace
    configuration_space:
      _target_: ConfigSpace.configuration_space.ConfigurationSpace.from_serialized_dict
      _convert_: object
      d:
        name: null
        hyperparameters:
        - type: uniform_float
          name: x0_cont
          lower: 0.1
          upper: 5.0
          default_value: 2.55
          log: false
          meta: null
        - type: uniform_float
          name: x1_cont
          lower: 0.1
          upper: 5.0
          default_value: 2.55
          log: false
          meta: null
        - type: uniform_float
          name: x2_cont
          lower: 0.01
          upper: 5.0
          default_value: 2.505
          log: false
          meta: null
        - type: uniform_float
          name: x3_cont
          lower: 0.01
          upper: 5.0
          default_value: 2.505
          log: false
          meta: null
        conditions: []
        forbiddens: []
        python_module_version: 1.2.0
        format_version: 0.4
    fidelity_space:
      _target_: carps.utils.task.FidelitySpace
      is_multifidelity: false
      fidelity_type: null
      min_fidelity: null
      max_fidelity: null
    instance_space: null
  output_space:
    _target_: carps.utils.task.OutputSpace
    n_objectives: 1
    objectives:
    - quality
  optimization_resources:
    _target_: carps.utils.task.OptimizationResources
    n_trials: 100
    time_budget: null
    n_workers: 1
  metadata:
    _target_: carps.utils.task.TaskMetadata
    has_constraints: false
    domain: real
    objective_function_approximation: real
    has_virtual_time: false
    deterministic: true
    dimensions: 4
    search_space_n_categoricals: 0
    search_space_n_ordinals: 0
    search_space_n_integers: 0
    search_space_n_floats: 4
    search_space_has_conditionals: false
    search_space_has_forbiddens: false
    search_space_has_priors: false
