# @package _global_
benchmark_id: PapenBench
task_id: PapenBench/1ramp_221020_17-18_speed
task:
  _target_: carps.utils.task.Task
  name: PapenBench/1ramp_221020_17-18_speed
  seed: ${seed}
  objective_function:
    _target_: carps.objective_functions.papenbench.PapenBenchObjectiveFunction
    benchmark_name: 1ramp_221020_17-18_speed
  input_space:
    _target_: carps.utils.task.InputSpace
    configuration_space:
      _target_: ConfigSpace.configuration_space.ConfigurationSpace.from_serialized_dict
      _convert_: object
      d:
        name: null
        hyperparameters:
        - type: uniform_int
          name: x0000
          lower: 1
          upper: 2500
          default_value: 1250
          log: false
          meta: null
        - type: uniform_int
          name: x0001
          lower: 1
          upper: 2500
          default_value: 1250
          log: false
          meta: null
        - type: uniform_int
          name: x0002
          lower: 1
          upper: 2500
          default_value: 1250
          log: false
          meta: null
        conditions: []
        forbiddens: []
        python_module_version: 1.2.0
        format_version: 0.4
    fidelity_space:
      _target_: carps.utils.task.FidelitySpace
      is_multifidelity: false
      fidelity_type: null
      min_fidelity: null
      max_fidelity: null
    instance_space: null
  output_space:
    _target_: carps.utils.task.OutputSpace
    n_objectives: 1
    objectives:
    - objective_0
  optimization_resources:
    _target_: carps.utils.task.OptimizationResources
    n_trials: 90
    time_budget: null
    n_workers: 1
  metadata:
    _target_: carps.utils.task.TaskMetadata
    has_constraints: false
    domain: TODO
    objective_function_approximation: TODO
    has_virtual_time: false
    deterministic: true
    dimensions: 3
    search_space_n_categoricals: 0
    search_space_n_ordinals: 0
    search_space_n_integers: 3
    search_space_n_floats: 0
    search_space_has_conditionals: false
    search_space_has_forbiddens: false
    search_space_has_priors: false
